development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: timecards_dev
  schema_search_path: 'public'
  pool: 5
  username: javier

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: timecards_test
  schema_search_path: 'public'
  pool: 5
  username: javier


production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: timecards_prod
  schema_search_path: 'public'
  pool: 5
  username: javier
